# Generated by Django 2.1.7 on 2019-04-08 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=3)),
                ('game', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('home', models.CharField(max_length=4, null=True)),
                ('opponent', models.CharField(max_length=3, null=True)),
                ('winorloss', models.CharField(max_length=1, null=True)),
                ('teampoints', models.IntegerField(null=True)),
                ('opponentpoints', models.IntegerField(null=True)),
                ('fieldgoals', models.IntegerField(null=True)),
                ('fieldgoalsattempted', models.IntegerField(null=True)),
                ('fieldgoalspercent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('x3pointshots', models.IntegerField(null=True)),
                ('x3pointshotsattempted', models.IntegerField(null=True)),
                ('x3pointshotspercent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('freethrows', models.IntegerField(null=True)),
                ('freethrowsattempted', models.IntegerField(null=True)),
                ('freethrowspercent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('offrebounds', models.IntegerField(null=True)),
                ('totalrebounds', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('steals', models.IntegerField(null=True)),
                ('blocks', models.IntegerField(null=True)),
                ('turnovers', models.IntegerField(null=True)),
                ('totalfouls', models.IntegerField(null=True)),
                ('oppfieldgoals', models.IntegerField(null=True)),
                ('oppfieldgoalsattempted', models.IntegerField(null=True)),
                ('oppfieldgoalspercent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('opp3pointshots', models.IntegerField(null=True)),
                ('opp3pointshotsattempted', models.IntegerField(null=True)),
                ('opp3pointshotspercent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('oppfreethrows', models.IntegerField(null=True)),
                ('oppfreethrowsattempted', models.IntegerField(null=True)),
                ('oppfreethrowspercent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('oppoffrebounds', models.IntegerField(null=True)),
                ('opptotalrebounds', models.IntegerField(null=True)),
                ('oppassists', models.IntegerField(null=True)),
                ('oppsteals', models.IntegerField(null=True)),
                ('oppblocks', models.IntegerField(null=True)),
                ('oppturnovers', models.IntegerField(null=True)),
                ('opptotalfouls', models.IntegerField(null=True)),
            ],
        ),
    ]
