# Generated by Django 2.1.7 on 2019-04-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='stats',
        ),
    ]
