# Generated by Django 2.1.7 on 2019-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0002_auto_20190408_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='teaminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamcode', models.CharField(max_length=3)),
                ('teamname', models.CharField(max_length=50)),
                ('teamsite', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
