# Generated by Django 2.1.7 on 2019-04-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0003_teaminfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminfo',
            old_name='teamsite',
            new_name='officialSite',
        ),
    ]
