# Generated by Django 2.1.7 on 2019-04-29 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0004_auto_20190428_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='found',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='officialSite',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
