# Generated by Django 2.1.7 on 2019-04-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0005_auto_20190429_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='twitter',
        ),
    ]
