# Generated by Django 2.1.7 on 2019-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0009_teamplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayers',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
