/*
-- Query: select * from nba_games_teaminfo
LIMIT 0, 1000

-- Date: 2019-05-01 16:34
*/
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (1,'ATL','Atlanta Hawks','https://www.nba.com/teams/hawks',1949,'State Farm Arena','Atlanta','Erie Bayhawks','Travis Schlenk','Lloyd Pierce','Tony Ressler',1,5);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (2,'BKN','Brooklyn Nets','https://www.nba.com/teams/nets',1976,'Barclays Center','Brooklyn','Long Island Nets','Sean Marks','Kenny Atkinson','Mikhail Prokhorov',0,6);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (3,'BOS','Boston Celtics','https://www.nba.com/teams/celtics',1946,'TD Garden','Boston','Maine Red Claws','Danny Ainge','Brad Stevens','Wyc Grousbeck',17,22);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (4,'CHA','Charlotte Hornets','https://www.nba.com/teams/hornets',1988,'Spectrum Center','Charlotte','Greensboro Swarm','Mitch Kupchak','James Borrego','Michael Jordan',0,1);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (5,'CHI','Chicago Bulls','https://www.nba.com/teams/bulls',1966,'United Center','Chicago','Windy City Bulls','Gar Forman','Jim Boylen','Jerry Reinsdorf',6,4);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (6,'CLE','Cleveland Cavaliers','https://www.nba.com/teams/cavaliers',1970,'Quicken Loans Arena','Cleveland','Canton Charge','Koby Altman','No Coach','Dan Gilbert',1,7);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (7,'DAL','Dallas Mavericks','https://www.nba.com/teams/mavericks',1980,'American Airlines Center','Dallas','Texas Legends','Donnie Nelson','Rick Carlisle','Mark Cuban',0,3);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (8,'DEN','Denver Nuggets','https://www.nba.com/teams/nuggets',1976,'Pepsi Center','Denver','None','Tim Connelly','Michael Malone','Stan Kroenke',0,7);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (9,'DET','Detroit Pistons','https://www.nba.com/teams/pistons',1948,'Little Caesars Arena','Detroit','Grand Rapids Drive','Ed Stefanski','Dwane Casey','Tom Gores',3,11);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (10,'GSW','Golden State Warriors','https://www.nba.com/teams/warriors',1946,'ORACLE Arena','Golden State','Santa Cruz Warriors','Bob Myers','Steve Kerr','Joe Lacob',6,6);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (11,'HOU','Houston Rockets','https://www.nba.com/teams/rockets',1967,'Toyota Center','Houston','Rio Grande Valley Vipers','Daryl Morey','Mike D\'Antoni','Tilman Fertitta',0,6);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (12,'IND','Indiana Pacers','https://www.nba.com/teams/pacers',1976,'Bankers Life Fieldhouse','Indiana','Fort Wayne Mad Ants','Kevin Pritchard','Nate McMillan','Herb Simon',0,5);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (13,'LAC','Los Angeles Clippers','https://www.nba.com/teams/clippers',1970,'Staples Center','Los Angeles','Agua Caliente Clippers of Ontario','Michael Winger','Doc Rivers','Steve Ballmer',0,0);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (14,'LAL','Los Angeles Lakers','https://www.nba.com/teams/lakers',1948,'Staples Center','Los Angeles','South Bay Lakers','Rob Pelinka','No Coach','Jerry Buss Family Trust',16,11);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (15,'MEM','Memphis Grizzlies','https://www.nba.com/teams/grizzlies',1995,'FedExForum','Memphis','Memphis Hustle','No Manager','No Coach','Robert Pera',0,2);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (16,'MIA','Miami Heat','https://www.nba.com/teams/heat',1988,'American Airlines Arena','Miami','Sioux Falls Skyforce','Pat Riley','Erik Spoelstra','Micky Arison',3,5);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (17,'MIL','Milwaukee Bucks','https://www.nba.com/teams/bucks',1968,'Fiserv Forum','Milwaukee','Wisconsin Herd','Jon Horst','Mike Budenholzer','Wesley Edens &˜Marc Lasry',1,8);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (18,'MIN','Minnesota Timberwolves','https://www.nba.com/teams/timberwolves',1989,'Target Center','Minnesota','Iowa Wolves','Scott Layden','Ryan Saunders','Glen Taylor',0,1);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (19,'NOP','New Orleans Pelicans','https://www.nba.com/teams/pelicans',2002,'Smoothie King Center','New Orleans','No Affiliate','No Manager','Alvin Gentry','Tom Benson',0,1);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (20,'NYK','New York Knicks','https://www.nba.com/teams/knicks',1946,'Madison Square Garden','New York','Westchester Knicks','Steve Mills','David Fizdale','Cablevision (James Dolan)',2,9);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (21,'OKC','Oklahoma City Thunder','https://www.nba.com/teams/thunder',1967,'Chesapeake Energy Arena','Oklahoma City','Oklahoma City Blue','Sam Presti','Billy Donovan','Clay Bennett',1,6);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (22,'ORL','Orlando Magic','https://www.nba.com/teams/magic',1989,'Amway Center','Orlando','Lakeland Magic','John Hammond','Steve Clifford','Rick DeVos',0,1);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (23,'PHI','Philadelphia 76ers','https://www.nba.com/teams/sixers',1949,'Wells Fargo Center','Philadelphia','Delaware Blue Coats','No Manager','Brett Brown','Joshua Harris',3,10);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (24,'PHX','Phoenix Suns','https://www.nba.com/teams/suns',1968,'Talking Stick Resort Arena','Phoenix','Northern Arizona Suns','James Jones','Igor Kokoskov','Robert Sarver',0,10);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (25,'POR','Portland Trail Blazers','https://www.nba.com/teams/blazers',1970,'Moda Center','Portland','No Affiliate','Neil Olshey','Terry Stotts','Paul Allen',1,12);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (26,'SAC','Sacramento Kings','https://www.nba.com/teams/kings',1948,'Golden 1 Center','Sacramento','Stockton Kings','Vlade Divac','Luke Walton','Vivek Ranadive',1,11);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (27,'SAS','San Antonio Spurs','https://www.nba.com/teams/spurs',1976,'AT&T Center','San Antonio','Austin Spurs','R. C. Buford','Gregg Popovich','Peter Holt',5,9);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (28,'TOR','Toronto Raptors','https://www.nba.com/teams/raptors',1995,'Scotiabank Arena','Toronto','Raptors 905','Masai Ujiri','Nick Nurse','Maple Leaf Sports and Entertainment',0,0);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (29,'UTA','Utah Jazz','https://www.nba.com/teams/jazz',1974,'Vivint Smart Home Arena','Utah','Salt Lake City Stars','Dennis Lindsey','Quin Snyder','Greg Miller',0,10);
INSERT INTO `nba_games_teaminfo` (`id`,`teamcode`,`teamname`,`officialSite`,`found`,`arena`,`city`,`g_league`,`general_manager`,`head_coach`,`owner`,`championships`,`retired_numbers`) VALUES (30,'WAS','Washington Wizards','https://www.nba.com/teams/wizards',1961,'Capital One Arena','Washington','Capital City Go-Go','No Manager','Scott Brooks','Ted Leonsis',1,5);
